### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by Anhetes** [solarsnoop/PCM60X-Monitor#1]
Hello, is there a possibility to impotate the data from the PCM60X in Grafana?

**Comment by solarsnoop** [comment]
sure, the code in the example show you how request the data from the PCM60x, after you can use the datas and post to every api depend on the form (eg MQTT).

**Comment by solarsnoop** [comment]
today i add a mqtt code example, with this you are able to post the charger values to your mqtt broker.
